### ISSUE TITLE
Please refrain from spoiling solutions to Codewars Kata

### ISSUE THREAD

**Issue by DonaldKellett** [lndgalante/codewars-katas#3]
From the [Codewars Community Code of Conduct](https://github.com/Codewars/codewars.com/wiki/Community-Code-of-Conduct):

> **Please do not post your solutions on Github.** We realize you would like to use these challenges as your resume, but you should have side-projects for that. If a Code Warrior is unable to find a solution online, then they are further encouraged to complete the task themselves - which will enable them to get more value out of their time spent.

Therefore, I would like to request for this repo to be made private, or at least state unambiguously in the README that:

- Codewarriors are strongly encouraged not to look at your solutions to Kata until they have completed it themselves or at least took the time to think about their own approaches
- Codewarriors should not submit your solutions as their own
- You will not be accepting contributions of any form to this repo
- Creating a repository like this is discouraged by Codewars

You are not obliged to abide by this request since this is your own work; however, cooperation on your part would be much appreciated.

See also: https://github.com/Codewars/codewars.com/issues/1378#issuecomment-567265654

**Comment by lndgalante** [comment]
Hey @DonaldKellett thanks for this! I will add those bullets to the README, maybe a Disclaimer section what's your thought ?. Can I accept PRs to improve existing katas or add new tests?

**Comment by DonaldKellett** [comment]
Thanks for cooperating :+1: I think PRs to improve existing (already solved) Kata and add new tests (for existing Kata only) would be fine, but try to avoid accepting PRs for solutions to previously unsolved Kata.

**Comment by Steffan153** [comment]
But remember, Github actually allows private repositories to be free now, so you can do that

**Comment by lndgalante** [comment]
Great @DonaldKellett I've added a **Disclaimer** section with that bullets points.
